#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1
start_service() {
 local enabled address port host interval
 config_load freeisp_tools
 config_get_bool enabled btest enabled 0
 config_get address btest address 127.0.0.1
 config_get port btest port 5201
 if [ "$enabled" = 1 ] && [ -x /usr/bin/iperf3 ]; then
  procd_open_instance bandwidth
  procd_set_param command /usr/bin/iperf3 -s -B "$address" -p "$port"
  procd_set_param respawn 3600 5 3
  procd_set_param stderr 1
  procd_close_instance
 fi
 config_get_bool enabled netwatch enabled 0
 if [ "$enabled" = 1 ]; then
  procd_open_instance netwatch
  procd_set_param command /usr/bin/ucode /usr/share/freeisp/netwatch.uc
  procd_set_param respawn 3600 5 3
  procd_set_param stderr 1
  procd_close_instance
 fi
}
service_triggers() { procd_add_reload_trigger freeisp_tools; }
