/* Loopback UI fixture. No router, credentials or network APIs are used. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const {chromium} = require('playwright');
const folder = path.resolve('desktop/FreeISP.Desk/Hub');
const output = path.resolve('artifacts/tests/local-interfaces');
fs.mkdirSync(output, {recursive: true});
const navigationSource = fs.readFileSync('openwrt/files/www/luci-static/freeisp/navigation.js', 'utf8');
const navigationBlock = navigationSource.match(/var entries = \[([\s\S]*?)\];/)[1];
const expectedNavigation = Array.from(navigationBlock.matchAll(/\['([^']+)', (null|'[^']+')\]/g), match => ({label: match[1], route: match[2] === 'null' ? null : match[2].slice(1, -1)}));
const navigationIcons = Array.from(navigationSource.match(/var paths = \[([\s\S]*?)\];/)[1].matchAll(/'([^']+)'/g), match => match[1]);
const remoteRoutes = expectedNavigation.filter(item => item.route && !['logout', 'network/freeisp_interfaces'].includes(item.route)).map(item => item.route);
const allowed = ['interfaces.html', 'interfaces.css', 'interfaces.js', 'hub.css', 'freeisp-logo.png'];
const server = http.createServer((req, res) => {
 const name = req.url.slice(1);
 if (!allowed.includes(name)) { res.writeHead(404); res.end(); return; }
 const type = name.endsWith('.js') ? 'text/javascript' : name.endsWith('.css') ? 'text/css' : name.endsWith('.png') ? 'image/png' : 'text/html';
 res.writeHead(200, {'Content-Type': type}); res.end(fs.readFileSync(path.join(folder, name)));
});
(async () => {
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
 const browser = await chromium.launch({headless: true, ...(process.env.FREEISP_BROWSER_CHANNEL ? {channel: process.env.FREEISP_BROWSER_CHANNEL} : {})});
 const checks = {};
 try {
  const page = await browser.newPage({viewport: {width: 1400, height: 1100}});
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
   window.bridgeMessages = []; window.emitNative = () => {};
   window.chrome = window.chrome || {};
   window.chrome.webview = {postMessage: message => window.bridgeMessages.push(message), addEventListener: (_, listener) => { window.emitNative = message => listener({data: message}); }};
   window.setFixtureHidden = hidden => { Object.defineProperty(document, 'hidden', {value: hidden, configurable: true}); document.dispatchEvent(new Event('visibilitychange')); };
  });
  await page.goto(`http://127.0.0.1:${server.address().port}/interfaces.html`);
  assert.equal(await page.locator('h1').innerText(), 'Interfaces');
  assert.equal(await page.locator('#interface-count').innerText(), '—');
  assert.equal(await page.evaluate(() => bridgeMessages.length), 0);
  assert(await page.locator('.original-logo').evaluate(image => image.naturalWidth > 0));
  checks.immediate_local_layout_and_original_logo = true;
  const menu = await page.locator('.freeisp-sidebar nav > *').evaluateAll(elements => elements.map(element => ({label: element.textContent.trim(), route: element.classList.contains('group') ? null : element.id === 'current-interfaces' ? 'network/freeisp_interfaces' : element.id === 'logout' ? 'logout' : element.dataset.route})));
  assert.deepEqual(menu, expectedNavigation);
  const icons = await page.locator('.freeisp-sidebar .fi-nav-icon path').evaluateAll(elements => elements.map(element => element.getAttribute('d')));
  assert.deepEqual(icons, expectedNavigation.filter(item => item.route).map((_, index) => navigationIcons[index % navigationIcons.length]));
  assert.equal(await page.locator('[aria-current=page]').innerText(), 'Interfaces');
  assert.equal(await page.locator('.freeisp-sidebar nav button').first().evaluate(element => getComputedStyle(element).fontSize), '13px');
  assert.equal(await page.locator('.freeisp-sidebar').evaluate(element => element.getBoundingClientRect().width), 218);
  assert.equal(await page.locator('#hub').count(), 0);
  checks.same_router_menu_order_icons_and_density = true;
  const emit = message => page.evaluate(message => emitNative(message), message);
  const count = () => page.evaluate(() => bridgeMessages.filter(m => m.action === 'interfacesSnapshot').length);
  await emit({type: 'interfaceContext', generation: 1, router: ''});
  await page.waitForTimeout(1100);
  assert.equal(await count(), 0); assert.equal(await page.locator('#connection-status').innerText(), 'Choose a router');
  assert(await page.locator('#settings').isDisabled());
  assert.equal(await page.locator('[data-route]:disabled').count(), remoteRoutes.length);
  assert(await page.locator('#logout').isDisabled());
  assert(await page.locator('#current-interfaces').isEnabled());
  checks.empty_router_stays_offline_without_polling = true;
  await emit({type: 'interfaceContext', generation: 10, router: 'Office gateway'});
  await page.waitForFunction(() => bridgeMessages.length === 1);
  await page.waitForTimeout(1200); assert.equal(await count(), 1);
  checks.no_overlapping_requests = true;
  const device = (rx, tx) => ({up: true, type: 'ethernet', mtu: 1500, statistics: {rx_bytes: rx, tx_bytes: tx, rx_packets: 0, tx_packets: 9}});
  const sample = (time, rx, tx) => ({type: 'interfaceSnapshot', generation: 10, sample: {sampleTime: time, devices: {eth0: device(rx, tx), unknown: {statistics: {}}}}});
  await emit(sample(1000, 1000, 2000));
  assert.equal(await page.locator('#rx-rate').innerText(), '—');
  assert.match(await page.locator('#interface-rows').innerText(), /Unknown/);
  assert.equal(await page.locator('#interface-rows tr').first().locator('td').nth(6).innerText(), '0');
  checks.unknown_not_zero_or_down = true;
  await page.waitForFunction(() => bridgeMessages.length === 2);
  await emit(sample(2000, 201000, 102000));
  assert.equal(await page.locator('#rx-rate').innerText(), '1.6 Mbps');
  assert.equal(await page.locator('#tx-rate').innerText(), '800 Kbps');
  assert(await page.locator('#rx-path').getAttribute('d'));
  assert.equal(await page.locator('#rx-point').getAttribute('visibility'), 'visible');
  checks.measured_rates_and_svg_chart = true;
  await page.screenshot({path: path.join(output, 'interfaces-day.png'), fullPage: true});
  await page.locator('#night').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'night');
  await page.screenshot({path: path.join(output, 'interfaces-night.png'), fullPage: true});
  checks.day_night = true;
  await page.locator('#search').fill('unknown');
  assert.equal(await page.locator('#interface-rows tr').count(), 1);
  await page.getByRole('button', {name: 'Show traffic for unknown'}).click();
  assert.equal(await page.locator('#rx-rate').innerText(), '—');
  await page.locator('#search').fill(''); await page.getByRole('button', {name: 'Show traffic for eth0'}).click();
  checks.search_and_selection = true;
  await emit({type: 'interfaceError', generation: 10, message: 'Test connection lost'});
  assert.match(await page.locator('#connection-status').innerText(), /Disconnected/);
  assert.equal(await page.locator('#rx-rate').innerText(), '1.6 Mbps');
  assert.match(await page.locator('#interface-rows').innerText(), /Up · last/);
  checks.stale_values_explicitly_disconnected = true;
  await page.evaluate(() => setFixtureHidden(true)); const hiddenCount = await count();
  await page.waitForTimeout(1200); assert.equal(await count(), hiddenCount);
  checks.hidden_page_stops_polling = true;
  await emit({type: 'interfaceContext', generation: 11, router: 'Second router'});
  assert.equal(await page.locator('#interface-count').innerText(), '—');
  await emit(sample(3000, 301000, 202000));
  await emit({type: 'interfaceContext', generation: 10, router: 'Old router'});
  assert.equal(await page.locator('#router').innerText(), 'Second router');
  assert.equal(await page.locator('#interface-count').innerText(), '—');
  checks.context_clears_values_and_rejects_old_generation = true;
  await page.evaluate(() => setFixtureHidden(false)); await page.waitForFunction(() => bridgeMessages.some(m => m.action === 'interfacesSnapshot' && m.generation === 11));
  await emit({type: 'interfaceSnapshot', generation: 11, sample: {sampleTime: 5000, devices: {'<img src=x onerror=alert(1)>': {statistics: {rx_bytes: '9007199254741000', tx_bytes: '10'}}}}});
  assert.equal(await page.locator('#interface-rows img').count(), 0);
  assert.match(await page.locator('#interface-rows').innerText(), /<img src=x/);
  checks.router_names_render_as_text = true;
  await page.locator('#settings').click(); await page.locator('#logout').click();
  await page.locator('#current-interfaces').click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'search');
  for (const button of await page.locator('[data-route]').all()) await button.click();
  const messages = await page.evaluate(() => bridgeMessages);
  assert(messages.some(m => m.action === 'openRouterPage' && m.route === 'network/freeisp_interfaces'));
  assert(messages.some(m => m.action === 'disconnect'));
  assert(!messages.some(m => m.action === 'hub' || m.route === 'logout'));
  for (const route of remoteRoutes) assert(messages.some(m => m.action === 'openRouterPage' && m.route === route));
  checks.native_navigation_contract = true;
  assert.deepEqual(errors, []); checks.no_browser_errors = true;
  fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({passed: true, checks}, null, 2));
  console.log(JSON.stringify({passed: true, checks}, null, 2));
 } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); server.close(); process.exitCode = 1; });
